### PR TITLE
Bind all compound literals to temporaries

### LINKED ISSUE #870: Introduce temporary bindings for struct-typed compound literals
PR #864 binds array-typed and function-typed compound literals to temporaries. This would allow bounds to be inferred for lvalue expressions such as `&(int [1]){ 0 }`. (see issue #859). The lvalue bounds of a struct-typed compound literal expression `e` should be `(&temp(e), &temp(e) + 1)`.

There are two issues that currently result from attempting to bind struct-typed compound literals to temporaries which should be fixed:

#### Assert failure in code generation
The assert `!E->getSubExpr()->isLValue())` fails in ScalarExprEmitter::VisitCHKCBindTemporaryExpr (CGExprScalar.cpp).

String literals and array-typed compound literals (which are both lvalues) are bound to temporaries. However, ScalarExprEmitter::VisitCHKBindTemporaryExpr is not called on these expressions since they are wrapped in ArrayToPointerDecay cast expressions rather than LValueToRValue cast expressions. For ArrayToPointerDecay casts, ScalarExprEmitter::VisitCastExpr calls CGF.EmitArrayToPointerDecay on the cast's subexpression. For LValueToRValue casts, ScalarExprEmitter::VisitCastExpr calls ScalarExprEmitter::Visit on the cast's subexpression.

#### Compile error for assignments involving a struct-typed literal
Assigning a struct-typed compound literal to a variable results in a compile error: "cannot compile this aggregate expression yet". For example:

```
struct S s;
s = (struct S){ 0 }; // error: cannot compile this aggregate expression yet

struct S s1 = (struct S){ 0 }; // no error
```

This error occurs because the AggExprEmitter class currently has no VisitCHKCBindTemporaryExpr method.

### PR DESCRIPTION
**Pull request by kkjeer**
Fixes #870 

This PR introduces temporary bindings for all compound literals. It also infers lvalue bounds for struct-typed compound literals: for a struct-typed compound literal expression `e`, the lvalue bounds of `e` are `bounds(&value(temp(e)), &value(temp(e)) + 1)`.

#### Testing:
* Modified bounds-context and compound-literals tests to expect compound literals and lvalue bounds for struct-typed compound literals
* Added checkedc tests in [checkedc/414](https://github.com/microsoft/checkedc/pull/414)
* Passed manual testing on Windows
* Passed automated testing on Windows/Linux

### CODE REVIEW

File: clang/lib/Sema/SemaBounds.cpp [hunk 1]
```diff
@@ -3684,21 +3684,33 @@ namespace {
...
+        // are bounds(&value(temp(e), &value(temp(e)) + 1).
+        if (E->getType()->isStructureType()) {
+          Expr *TempUse = CreateTemporaryUse(E);
+          Expr *Addr = CreateAddressOfOperator(TempUse);
+          const llvm::APInt One(Context.getTargetInfo().getPointerWidth(0), 1);
+          IntegerLiteral *Size = CreateIntegerLiteral(One);
+          CountBoundsExpr *CBE = new (Context)
+              CountBoundsExpr(BoundsExpr::Kind::ElementCount, Size,
+                              SourceLocation(), SourceLocation());
+          return ExpandToRange(Addr, CBE);
```
Comment (dtarditi) [inline clang/lib/Sema/SemaBounds.cpp:3697]: There's a prebuilt Count(1) expression available in ASTContext.  See ASTContext::getPrebuiltCountOne().   This avoids an extra allocation in ASTContext.  The code constructs a count(1) expression, but then calls ExpandToRange, which produces a range expression.

File: clang/lib/Sema/SemaBounds.cpp [hunk 2]
```diff
@@ -3684,21 +3684,33 @@ namespace {
...
+
         // Only expressions with array or function type can have a decayed
-        // type, which is used to create the lvalue bounds.  Compound literals
-        // with non-array, non-function types do not have lvalue bounds.
-        // TODO: checkedc-clang issue #870: bind all compound literals to
-        // temporaries and infer lvalue bounds for struct compound literals.
-        if (!(E->getType()->isArrayType() || E->getType()->isFunctionType()))
-          return CreateBoundsAlwaysUnknown();
+        // type, which is used to create the lvalue bounds.
+        if (E->getType()->isArrayType() || E->getType()->isFunctionType()) {
```
Comment (dtarditi) [inline clang/lib/Sema/SemaBounds.cpp:3702]: I don't think function types should have bounds, so I'm confused by the prior code.  Should function types be given unknown bounds instead?
